Collecting numpy
  Using cached numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
Collecting requests[socks]
  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
  Using cached requests-2.29.0-py3-none-any.whl (62 kB)
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
  Using cached requests-2.28.0-py3-none-any.whl (62 kB)
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
  Using cached requests-2.27.0-py2.py3-none-any.whl (63 kB)
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Building wheels for collected packages: lap, lapsolver, pycocotools
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-9_a4x5es/lap_367a6ba037b74cf2a0ceef68af02293c/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9_a4x5es/lap_367a6ba037b74cf2a0ceef68af02293c/setup.py", line 236, in <module>
          setup_package()
        File "/tmp/pip-install-9_a4x5es/lap_367a6ba037b74cf2a0ceef68af02293c/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
  Building wheel for lapsolver (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [141 lines of output]
      /home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/lapsolver
      copying lapsolver/__init__.py -> build/lib.linux-x86_64-cpython-37/lapsolver
      creating build/lib.linux-x86_64-cpython-37/lapsolver/tests
      copying lapsolver/tests/__init__.py -> build/lib.linux-x86_64-cpython-37/lapsolver/tests
      copying lapsolver/tests/test_dense.py -> build/lib.linux-x86_64-cpython-37/lapsolver/tests
      copying lapsolver/tests/test_files.py -> build/lib.linux-x86_64-cpython-37/lapsolver/tests
      running egg_info
      writing lapsolver.egg-info/PKG-INFO
      writing dependency_links to lapsolver.egg-info/dependency_links.txt
      writing top-level names to lapsolver.egg-info/top_level.txt
      reading manifest file 'lapsolver.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'lapsolver.egg-info/SOURCES.txt'
      /home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'lapsolver.data.dense' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'lapsolver.data.dense' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'lapsolver.data.dense' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'lapsolver.data.dense' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      /home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'lapsolver.etc' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'lapsolver.etc' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'lapsolver.etc' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'lapsolver.etc' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-37/lapsolver/data
      creating build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs0.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs1.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs10.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs2.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs3.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs4.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs5.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs6.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs7.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs8.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      copying lapsolver/data/dense/costs9.npz -> build/lib.linux-x86_64-cpython-37/lapsolver/data/dense
      creating build/lib.linux-x86_64-cpython-37/lapsolver/etc
      copying lapsolver/etc/benchmark-dtype-int.png -> build/lib.linux-x86_64-cpython-37/lapsolver/etc
      copying lapsolver/etc/benchmark-dtype-numpy.float32.png -> build/lib.linux-x86_64-cpython-37/lapsolver/etc
      running build_ext
      Traceback (most recent call last):
        File "/tmp/pip-install-9_a4x5es/lapsolver_17328f06e4c14c8cb235085af20b697c/setup.py", line 22, in run
          out = subprocess.check_output(['cmake', '--version'])
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/subprocess.py", line 411, in check_output
          **kwargs).stdout
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/subprocess.py", line 488, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/subprocess.py", line 1551, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9_a4x5es/lapsolver_17328f06e4c14c8cb235085af20b697c/setup.py", line 88, in <module>
          keywords='hungarian munkres kuhn linear-sum-assignment bipartite-graph lap'
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-9_a4x5es/lapsolver_17328f06e4c14c8cb235085af20b697c/setup.py", line 25, in run
          ", ".join(e.name for e in self.extensions))
      RuntimeError: CMake must be installed to build the following extensions: lapsolverc
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lapsolver
  Running setup.py clean for lapsolver
  Building wheel for pycocotools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      /home/user/anaconda3/envs/tracktor/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-37/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-37/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-37/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-37/pycocotools
      running build_ext
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      /tmp/pip-install-9_a4x5es/pycocotools_9d78fde8fc044cefa0f1c661a7726f55/.eggs/Cython-3.0.10-py3.7-linux-x86_64.egg/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-9_a4x5es/pycocotools_9d78fde8fc044cefa0f1c661a7726f55/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'pycocotools._mask' extension
      creating build/common
      creating build/temp.linux-x86_64-cpython-37
      creating build/temp.linux-x86_64-cpython-37/common
      creating build/temp.linux-x86_64-cpython-37/pycocotools
      gcc -pthread -B /home/user/anaconda3/envs/tracktor/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-install-9_a4x5es/pycocotools_9d78fde8fc044cefa0f1c661a7726f55/.eggs/numpy-1.21.6-py3.7-linux-x86_64.egg/numpy/core/include -I./common -I/home/user/anaconda3/envs/tracktor/include/python3.7m -c ../common/maskApi.c -o build/temp.linux-x86_64-cpython-37/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      cc1: fatal error: ../common/maskApi.c: No such file or directory
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
Failed to build lap lapsolver pycocotools
Installing collected packages: lap, keras, jsonpickle, ipython-genutils, iniconfig, flatbuffers, filelock, enum34, easydict, docopt, dataclasses, clang, certifi, cachetools, cached-property, backcall, xmltodict, wurlitzer, Werkzeug, urllib3, tqdm, tornado, toml, tensorboard-data-server, smmap2, six, rsa, pyzmq, PyYAML, PySocks, pyparsing, Pygments, pyflakes, pycodestyle, pyasn1-modules, py, Pillow, pexpect, oauthlib, numpy, more-itertools, MarkupSafe, lazy-object-proxy, lapsolver, kiwisolver, jedi, isort, idna, gast, future, entrypoints, defusedxml, decorator, Cython, colorama, chardet, beautifulsoup4, attrs, zipp, yacs, traitlets, tifffile, terminado, scipy, requests, PyWavelets, python-dateutil, pyrsistent, protobuf, prompt-toolkit, packaging, opt-einsum, opencv-python, networkx, munch, Keras-Preprocessing, Jinja2, imageio, h5py, grpcio, google-pasta, google-auth, google, gitdb2, flake8-import-order, fastdtw, cycler, bleach, astunparse, astroid, absl-py, tensorboardX, requests-oauthlib, pylint, pandas, matplotlib, jupyter-core, ipython, importlib-metadata, GitPython, seaborn, scikit-image, sacred, pycocotools, pluggy, Markdown, jupyter-client, jsonschema, google-auth-oauthlib, gdown, flake8, tensorboard, pytest, nbformat, ipykernel, tensorflow, qtconsole, pytest-benchmark, nbconvert, metakernel, jupyter-console, notebook, motmetrics, matlab-kernel, widgetsnbextension, jupyter-http-over-ws, ipywidgets, jupyter
  Running setup.py install for lap ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-9_a4x5es/lap_367a6ba037b74cf2a0ceef68af02293c/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9_a4x5es/lap_367a6ba037b74cf2a0ceef68af02293c/setup.py", line 236, in <module>
          setup_package()
        File "/tmp/pip-install-9_a4x5es/lap_367a6ba037b74cf2a0ceef68af02293c/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

